Updates for pay_certs

diff --git a/config/add_global_usertag b/config/add_global_usertag
--- a/config/add_global_usertag
+++ b/config/add_global_usertag
@@ -25,11 +25,21 @@ else
 		|| die "Cannot make $TAGDIR"
 fi
 
-for f in *.tag
+for f in *.tag *.am
 do
 	if test -f __MVC_RELOCATE____MVC_VENDROOT__/usertag/$f
 	then
 		echo "$f appears to be in global usertag/ directory, skipping."
+	else
+		cp $f $TAGDIR || die "Cannot copy $f to $TAGDIR: $!"
+	fi
+done
+
+for f in *.filter
+do
+	if test -f __MVC_RELOCATE____MVC_VENDROOT__/filter/$f
+	then
+		echo "$f appears to be in global filter/ directory, skipping."
 	else
 		cp $f $TAGDIR || die "Cannot copy $f to $TAGDIR: $!"
 	fi
